### PR TITLE
Add hosting guide

### LINKED ISSUE #4: Add how-to-host.md
### Feature request
Currently there is no text tutorial on how to host the bot, a file should be added that explains all the steps needed to host the bot yourself, it should also mention the need of external programs like Node.js.
This file should be located in the root directory and be pointed to in the README.md.

Adding a how-to-host.md will make it easier for other people to host the bot without much knowledge about Discord bots or development in Node.js.

### PR DESCRIPTION
**Pull request by Victoria-DR**
Added a guide on how to host the bot locally, located in the root directory. The guide has been linked to in the README.

Closes #4

### CODE REVIEW

**Comment by DanielKnerr** [comment]
I believe there are a few issues with this:
1. `node deploy-commands.ts` doesn't work, since Node.js can't execute TypeScript. The `dist` folder was removed from the repository since the last release, so a user would first have to compile the source with `tsc` and then call `node dist/deploy-commands.js`.
2. `npm start` doesn't work since there is no `start` script.
3. I think it's worth mentioning that the bot looks for a `music` folder in *parent directory* of the current working directory. It took me a while to figure that out.

**Review by Daanisaanwezig — CHANGES_REQUESTED** [review]
Hey, I love the how-to-host.md, however there are a couple of points that need to be fixed.

1. It says that you need Node.js v16.9.1 or later, this should be v16.6 or later.
2. The bot needs the `applications.commands` permission to register the slash commands.
3. When running the bot the user should go to the `dist` folder, this is the folder containing the JavaScript files that can be run using the node prefix. First they should run `node deploy-commands` and after they need to run `node index` to start the bot.

So if you could fix those points I would say this is a really good rundown on how to host the bot.

**Comment by Daanisaanwezig** [comment]
> I believe there are a few issues with this:
> 
> 1. `node deploy-commands.ts` doesn't work, since Node.js can't execute TypeScript. The `dist` folder was removed from the repository since the last release, so a user would first have to compile the source with `tsc` and then call `node dist/deploy-commands.js`.
> 2. `npm start` doesn't work since there is no `start` script.
> 3. I think it's worth mentioning that the bot looks for a `music` folder in _parent directory_ of the current working directory. It took me a while to figure that out.

Ah you beat me to it.
For the first and last point, the releases (once the bot will be fully released) will get a music and dist folder containing all the files needed to start running the bot, but some information on how the music folder works could be nice indeed.

**Comment by Victoria-DR** [comment]
Added the changes you requested. I did change the Node version from 16.9.1 to 16.6 or later, but do note that the version in `package.json` is 16.9.1. I'd change this to `^16.6.0`.

**Review by Daanisaanwezig — APPROVED** [review]

**Pull request merged**
